potential:
  ground_truth: "styblinski"
  features: [32, 32]

grid:
  scale: 4.5
  number: 100

population:
  n_cells: 10
  n_genes: 2
  n_dims: 2

evolution:
  n_timepoints: 15

model:
  tau: 1.0
  n_iter: 1
  batch_iter: 500
  batch_size:
  learning_rate: 0.01
  quadratic: false
  teacher_forcing: true

wandb:
  mode: "online"

defaults:
  - _self_
  - override hydra/launcher: gpu
