dataset_path: "/pasteur/zeus/projets/p02/ml4ig_hot/Users/ghuizing/data/artista/artista_traj_processed.h5ad"
omics_key: "X_pca_harmony"
space_key: "spatial"
weight_key: "growth"
annotation_key: "Annotation"
time_key: "time"
train_batches: [Injury_2DPI_rep1_SS200000147BL_D5,Injury_5DPI_rep1_SS200000147BL_D2,Injury_10DPI_rep1_SS200000147BL_B5,Injury_15DPI_rep4_FP200000266TR_E4,Injury_20DPI_rep2_SS200000147BL_B4,Injury_30DPI_rep2_FP200000264BL_A6]
early_test_batches: []
late_test_batches: []
