dataset_path: "/pasteur/zeus/projets/p02/ml4ig_hot/Users/ghuizing/data/dorsal_midbrain/dorsal_midbrain_processed.h5ad"
omics_key: "X_pca_harmony"
space_key: "spatial"
weight_key: "growth"
annotation_key: "annotation"
time_key: "time"
train_batches: [FP200000600TR_E3,SS200000108BR_A3A4,SS200000108BR_B1B2]
early_test_batches: []
late_test_batches: []
