dataset_path: "/pasteur/zeus/projets/p02/ml4ig_hot/Users/ghuizing/data/mosta/mosta_processed.h5ad"
omics_key: "X_pca_harmony"
space_key: "spatial"
weight_key: null
annotation_key: "annotation"
time_key: "time"
train_batches: [E9.5_E1S1,E10.5_E1S1,E11.5_E1S1,E12.5_E1S1,E13.5_E1S1,E14.5_E1S1,E15.5_E1S1]
early_test_batches: [E13.5_E1S2,E14.5_E1S2]
late_test_batches: [E15.5_E1S2,E16.5_E1S1]
