dataset_path: "/pasteur/appa/scratch/ghuizing/spatial_sixtime_slice_stereoseq_processed.h5ad"
space_obsm: "spatial"
obsm: "X_pca_harmony"
viz_obsm: "X_umap"
annotation_obs: "bin_annotation"
time_obs: "time"
