skip_last: true
checkpoint_path: tmp/lin_zesta_lecun
n_pcs: 2
model:
  epsilon: 0.01
  tau: 1.0
  teacher_forcing: true
  quadratic: false
  fused: 1.0
  seed: 19225
potential:
  features:
  - 128
  - 128
  - 128
step:
  type: linear_explicit
  implicit_diff: true
  maxiter: 100
optimizer:
  train_val_split: 0.8
  learning_rate: 0.0001
  checkpoint_interval: 1
  max_epochs: 500
  batch_size: 100
  min_delta: 0.001
  patience: 20
wandb:
  mode: offline
organism:
  dataset_path: /pasteur/appa/scratch/ghuizing/spatial_sixtime_slice_stereoseq_processed.h5ad
  space_obsm: spatial
  obsm: X_pca_harmony
  viz_obsm: X_umap
  annotation_obs: bin_annotation
  time_obs: time
