dataset:
  path: "/users/csb/huizing/Documents/PhD/Data/axolotl/Regeneration_processed.h5ad"
  obsm: "X_umap"
  time_obs: "time"

model:
  tau: 0.001
  debias: True
  epsilon: 0.01
  seed: 0

potential:
  features: [64, 64]

optimizer:
  learning_rate: 0.01
  n_iter: 100
  batch_iter: 100
  batch_size: 50

plot:
  title: "Energy landscape of Axolotl brain regeneration"
  contour:
    levels: 30
    alpha: 0.5
    linewidths: 0.5
  scatter:
    size: 1
    alpha: 1
    cmap: "viridis"
