dataset:
  path: "/users/csb/huizing/Documents/PhD/Data/c_elegans_embryos/c_elegans_embryos.h5ad"
  obsm: "X_phate"
  time_obs: "time"

model:
  tau: 0.001
  debias: True
  epsilon: 0.01
  seed: 0
  proximal_step: "linear_implicit"

potential:
  features: [64, 64]

optimizer:
  learning_rate: 0.01
  n_iter: 50
  batch_iter: 50
  batch_size: 5

plot:
  title: "Energy landscape of C elegans embroyogenesis"
  contour:
    levels: 30
    alpha: 0.5
    linewidths: 0.5
  scatter:
    size: 20
    alpha: 1
    cmap: "viridis"