# Configuration for Weights & Biases
wandb:
  mode: "online"

checkpoint_path: ???

hydra:
  sweeper:
    params:
      checkpoint_path: tmp/linear_mosta_11135,tmp/linear_mosta_21470,tmp/linear_mosta_27630,tmp/linear_mosta_32046,tmp/linear_mosta_5611,tmp/quad_mosta_01_16935,tmp/quad_mosta_01_24721,tmp/quad_mosta_01_24727,tmp/quad_mosta_01_30074,tmp/quad_mosta_01_31373,tmp/quad_mosta_05_11315,tmp/quad_mosta_05_24242,tmp/quad_mosta_05_27919,tmp/quad_mosta_05_4185,tmp/quad_mosta_05_9681,tmp/quad_mosta_1_17390,tmp/quad_mosta_1_20010,tmp/quad_mosta_1_26208,tmp/quad_mosta_1_31874,tmp/quad_mosta_1_3206
