model:
  epsilon: 0.01
  teacher_forcing: true
  quadratic: false
  seed: 0

potential:
  features: [64, 64]

optimizer:
  learning_rate: 0.01
  n_iter: 1
  batch_iter: 1_000
  batch_size:

plot:
  title: "Energy landscape"
  contour:
    levels: 30
    alpha: 0.5
    linewidths: 0.5
  scatter:
    size: 10
    alpha: 1
    cmap: "viridis"

wandb:
  mode: "online"
